In [ ]:
import pandas as pd
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
df = pd.read_csv("letter-recognition.csv")
df

       T  2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0      I  5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1      D  4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2      N  7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3      G  2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4      S  4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7
...   .. ..  .. .. .. ..  ...  .. .. ..  ...  ..  ...  ...  ...  ...  ...
19994  D  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  C  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  T  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  S  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  A  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

[19999 rows x 17 columns]

In [ ]:
display(df.shape)
df.dropna()
display(df.shape)

(19999, 17)

(19999, 17)

In [ ]:
X = df.drop(columns = ["T"])
display(X)

y = df['T']
display(y)

       2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0      5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1      4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2      7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3      2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4      4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7
...   ..  .. .. .. ..  ...  .. .. ..  ...  ..  ...  ...  ...  ...  ...
19994  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

[19999 rows x 16 columns]

0        I
1        D
2        N
3        G
4        S
        ..
19994    D
19995    C
19996    T
19997    S
19998    A
Name: T, Length: 19999, dtype: object

In [ ]:
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
display(X_train)

       2   8   3  5  1  8.1  13   0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
5894   4  12   4  8  3    4  11  10  3    9   6    4    2   10    4    8
3728   1   1   2  1  0    8   9   2  2    7  12    8    1   10    0    8
8958   7  11  10  8  6    8   7   2  9   11   6    9    5    7    6    8
7671   2   3   3  2  2    6   7   5  5    9   7   10    2    9    4    9
5999   3   4   4  3  2    5   8   5  7    9   8    9    3   10    2    5
...   ..  ..  .. .. ..  ...  ..  .. ..  ...  ..  ...  ...  ...  ...  ...
11284  3   2   3  4  1    3   7   7  2    7   7   11    3    8    3   10
11964  2   4   4  3  3    8   7   3  5   10   6    7    2    8    4    9
5390   3   3   3  5  1    0   1   6  6    0   1    5    0    8    0    8
860    8  11   8  8  4    2  11   3  6   12  12    7    1   11    2    5
15795  2   6   3  4  2    1  10   3  5   11  11    9    0    8    2    7

[15999 rows x 16 columns]

In [ ]:
scalar = StandardScaler()

X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(16,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(26, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.1
)

Epoch 1/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6027 - loss: 1.4734 - val_accuracy: 0.7538 - val_loss: 0.8233
Epoch 2/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8089 - loss: 0.6715 - val_accuracy: 0.8169 - val_loss: 0.6076
Epoch 3/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8530 - loss: 0.5055 - val_accuracy: 0.8406 - val_loss: 0.4990
Epoch 4/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8785 - loss: 0.4119 - val_accuracy: 0.8806 - val_loss: 0.4086
Epoch 5/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8985 - loss: 0.3430 - val_accuracy: 0.8956 - val_loss: 0.3473
Epoch 6/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9128 - loss: 0.2940 - val_accuracy: 0.9081 - val_loss: 0.3234
Epoch 7/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9251 - loss: 0.2570 - val_accuracy: 0.9156 - val_loss: 0.2976
Epoch 8/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9322 - loss: 0.2270 - val_accuracy: 0.9250 - val_loss: 0.2703
Epoch 9/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9388 - loss: 0.2033 - val_accuracy: 0.9231 - val_loss: 0.2452
Epoch 10/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9449 - loss: 0.1836 - val_accuracy: 0.9294 - val_loss: 0.2329
Epoch 11/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9484 - loss: 0.1689 - val_accuracy: 0.9356 - val_loss: 0.2208
Epoch 12/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9540 - loss: 0.1533 - val_accuracy: 0.9319 - val_loss: 0.2171
Epoch 13/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9560 - loss: 0.1421 - val_accuracy: 0.9350 - val_loss: 0.2157
Epoch 14/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9610 - loss: 0.1306 - val_accuracy: 0.9369 - val_loss: 0.2037
Epoch 15/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9646 - loss: 0.1200 - val_accuracy: 0.9419 - val_loss: 0.1935
Epoch 16/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9656 - loss: 0.1143 - val_accuracy: 0.9331 - val_loss: 0.2044
Epoch 17/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9684 - loss: 0.1044 - val_accuracy: 0.9450 - val_loss: 0.1803
Epoch 18/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9712 - loss: 0.0969 - val_accuracy: 0.9463 - val_loss: 0.1732
Epoch 19/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9713 - loss: 0.0928 - val_accuracy: 0.9431 - val_loss: 0.1742
Epoch 20/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9734 - loss: 0.0867 - val_accuracy: 0.9494 - val_loss: 0.1686

In [ ]:
loss,accuracy = model.evaluate(X_test, y_test)

print("Accuracy: ",accuracy)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9420 - loss: 0.1752
Accuracy:  0.9419999718666077

In [ ]:
y_pred = model.predict(X_test)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [ ]:
predicted_class = np.argmax(y_pred[0])

print(predicted_class)

23

In [ ]:
letter = encoder.inverse_transform([predicted_class])

print(letter)

['X']

In [ ]:
#2b from here

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
# We will only keep the 10,000 most frequent words in the training data to avoid weird typos
vocab_size = 10000

print("Loading data...")
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=vocab_size)

print(f"Training entries: {len(X_train)}, Labels: {len(y_train)}")
print(f"Example review (in numbers): {X_train[0][:10]}...")

Loading data...
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/imdb.npz
17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Training entries: 25000, Labels: 25000
Example review (in numbers): [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65]...

In [ ]:
max_length = 256

X_train = pad_sequences(X_train, maxlen=max_length, padding='post', value=0)
X_test = pad_sequences(X_test, maxlen=max_length, padding='post', value=0)

print(f"New shape of training data: {X_train.shape}")

New shape of training data: (25000, 256)

In [ ]:
model = Sequential()

# 1. The Embedding Layer: Turns integer words into dense vectors of meaning
model.add(Embedding(vocab_size, 16))

# 2. Global Average Pooling: Squashes the sequence down so the Dense layer can read it
model.add(GlobalAveragePooling1D())

# 3. Hidden Dense Layer
model.add(Dense(16, activation='relu'))

# 4. Output Layer
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ ?                      │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=512,
    validation_split=0.2
)

Epoch 1/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - accuracy: 0.5853 - loss: 0.6907 - val_accuracy: 0.6386 - val_loss: 0.6849
Epoch 2/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.7074 - loss: 0.6755 - val_accuracy: 0.7164 - val_loss: 0.6606
Epoch 3/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.7384 - loss: 0.6425 - val_accuracy: 0.7650 - val_loss: 0.6169
Epoch 4/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7845 - loss: 0.5900 - val_accuracy: 0.7904 - val_loss: 0.5595
Epoch 5/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.8130 - loss: 0.5279 - val_accuracy: 0.8116 - val_loss: 0.5002
Epoch 6/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.8226 - loss: 0.4706 - val_accuracy: 0.8190 - val_loss: 0.4518
Epoch 7/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.8503 - loss: 0.4156 - val_accuracy: 0.8466 - val_loss: 0.4083
Epoch 8/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.8639 - loss: 0.3761 - val_accuracy: 0.8238 - val_loss: 0.3964
Epoch 9/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.8686 - loss: 0.3498 - val_accuracy: 0.8494 - val_loss: 0.3644
Epoch 10/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.8766 - loss: 0.3259 - val_accuracy: 0.8544 - val_loss: 0.3493
Epoch 11/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.8882 - loss: 0.3027 - val_accuracy: 0.8680 - val_loss: 0.3294
Epoch 12/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8931 - loss: 0.2886 - val_accuracy: 0.8694 - val_loss: 0.3216
Epoch 13/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.8990 - loss: 0.2734 - val_accuracy: 0.8746 - val_loss: 0.3121
Epoch 14/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.9028 - loss: 0.2618 - val_accuracy: 0.8758 - val_loss: 0.3064
Epoch 15/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.9090 - loss: 0.2500 - val_accuracy: 0.8734 - val_loss: 0.3036
Epoch 16/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - accuracy: 0.9110 - loss: 0.2414 - val_accuracy: 0.8656 - val_loss: 0.3104
Epoch 17/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.9127 - loss: 0.2340 - val_accuracy: 0.8832 - val_loss: 0.2918
Epoch 18/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9193 - loss: 0.2226 - val_accuracy: 0.8722 - val_loss: 0.2995
Epoch 19/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - accuracy: 0.9186 - loss: 0.2179 - val_accuracy: 0.8746 - val_loss: 0.2968
Epoch 20/20
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.9209 - loss: 0.2133 - val_accuracy: 0.8708 - val_loss: 0.3014

In [ ]:
loss, accuracy = model.evaluate(X_test,  y_test)
print(f"Accuracy: {accuracy * 100:.2f}%")

# Let's see what it predicts for the first test review
prediction = model.predict(X_test[:1])
sentiment = "Positive" if prediction[0][0] > 0.5 else "Negative"

print(f"Model Prediction: {sentiment} ({prediction[0][0]:.4f})")
print(f"Actual Label: {'Positive' if y_test[0] == 1 else 'Negative'}")

782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8651 - loss: 0.3121
Accuracy: 86.51%
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
Model Prediction: Negative (0.0703)
Actual Label: Negative